### ISSUE TITLE
CRUD example against local SQL Server fails to retrieve data at Index

### ISSUE THREAD

**Issue by fperez2511** [OrchardSkills/OrchardSkills.OrchardCore.CRUD#2]
Description: 
Web Application crashes with -> Incorrect syntax near OFFSET after trying to create a tenant with a local SQL Server database.

Prerequisites:
- Visual Studio 2019 Professional
- SQL Server 2014

Steps to reproduce:
- Clone the OrchardSkills.OrchardCore.CRUD repo.
- Upgrade NUGET packages to 1.0.0-rc2-13490 (according to video).
- Start the web application.
- Create a new tenant with SQL Server as the storage database and use CRUD recipe.
- Finish Set up and then navigate to new tenant. The `HomeController.cs` will crash at the `Index()` operation with the following error: 

`{"ClassName":"Microsoft.Data.SqlClient.SqlException","Message":"Incorrect syntax near 'OFFSET'.\r\nInvalid usage of the option NEXT in the FETCH statement.","Data":{"HelpLink.ProdName":"Microsoft SQL Server","HelpLink.ProdVer":"12.00.4100","HelpLink.EvtSrc":"MSSQLServer","HelpLink.EvtID":"102","HelpLink.BaseHelpUrl":"http://go.microsoft.com/fwlink","HelpLink.LinkId":"20476","SqlError 1":"Microsoft.Data.SqlClient.SqlError: Incorrect syntax near 'OFFSET'.","SqlError 2":"Microsoft.Data.SqlClient.SqlError: Invalid usage of the option NEXT in the FETCH statement."},"InnerException":null,"HelpURL":null,"StackTraceString":"   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__164_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at YesSql.Store.ProduceAsync[T](WorkerQueryKey key, Func`2 work, Object[] args)\r\n   at YesSql.Services.DefaultQuery.Query`1.ListImpl()\r\n   at OrchardCore.CRUD.Controllers.HomeController.Index(PagerParameters pagerParameters) in C:\\Users\\fperez\\Source\\Repos\\OrchardSkills.OrchardCore.CRUD\\OrchardCore.CRUD\\Controllers\\HomeController.cs:line 73","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2146232060,"Source":"Core Microsoft SqlClient Data Provider","WatsonBuckets":null,"Errors":null,"ClientConnectionId":"02588798-1ef9-4579-947b-95edb37d301a"}`

**Comment by OrchardSkills** [comment]
I need more information

**Comment by OrchardSkills** [comment]
This is a database configuration issue

**Comment by fleccy** [comment]
I had this issue (MSSQL 2016). I removed this line which resolved the issue: 
Line 70: HomeController.cs
IEnumerable<ContentItem> model = await query.ListAsync();

Once I removed this, it worked fine - this line doesn't appear to be required anyway.
